ft-user-register-#182711347
iyaremye-faustin/G11-Backend pull request #4
Opened 2022-07-20 08:51 UTC by Prebero

### User registration
User should be able to regiter to WeForYouth Application
### Branch name 
ft-user-registration-182711347
### Api End points/routes
api/register
### How to test this Task
Given that the server application is running you can visit the api documentation at ....... and use register api in User Tag with provided data needed in the request.

2022-07-20 09:51 UTC, iyaremye-faustin requested changes

2022-07-20 09:51 UTC, iyaremye-faustin commented on app/Http/Controllers/Auth/RegistrationController.php
> +            'community' => $request->community,
This should be a relationship between communities and user, so implement communities table allow user to select from once registering. Please check well in the task description. cc https://www.pivotaltracker.com/n/projects/2580994

2022-07-20 09:51 UTC, iyaremye-faustin commented on app/Http/Controllers/Auth/RegistrationController.php
> +            $details = [
All your codes inside function should be inside try and catch block why only email sending? And your catch all possible errors and handle them accordingly

2022-07-23 06:12 UTC, iyaremye-faustin commented on app/Http/Controllers/Auth/RegistrationController.php
> +            'community' => $request->community_id,
request has community instead of community_id based on your validation

2022-07-23 06:12 UTC, iyaremye-faustin commented on app/Http/Controllers/Auth/RegistrationController.php
> +        ], 200);
Add also status property in the response

2022-07-23 06:14 UTC, iyaremye-faustin commented on app/Http/Controllers/Auth/RegistrationController.php
> +            'user' => $user->refresh(),
remove {email_verified_at,community_id} in the user for response

2022-07-23 06:14 UTC, iyaremye-faustin commented on app/Mail/RegistrationEmail.php
> +        return $this->subject("Registration_EMAIL")->view("email");
You didnot work on this, please take care

2022-07-23 06:16 UTC, iyaremye-faustin commented on database/migrations/2014_10_12_000000_create_users_table.php
>          });
use uuid type of id field to add more security, you forgot this

2022-07-23 06:16 UTC, iyaremye-faustin commented on database/migrations/2022_07_21_151737_create_communities_table.php
> +            $table->string('name')->unique();
Add description field here

2022-07-23 06:17 UTC, iyaremye-faustin commented on database/seeders/CommunitySeeder.php
> +}
configure your editor to add new lines after codes block in the file

2022-07-23 06:18 UTC, iyaremye-faustin reviewed
Great work man, few changes to get it done.

2022-07-23 16:37 UTC, Prebero commented on database/seeders/CommunitySeeder.php
> +}
which extension should i use?

2022-07-23 18:58 UTC, iyaremye-faustin approved these changes

2022-07-23 18:59 UTC, merged